name: Update Samples

on:
  push:
    branches:
      - master

jobs:
  update-samples:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Check for changes in Assets/Carousel
        id: check_changes
        run: |
          # Get the list of changed files in the last commit
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          
          # Check if any files in Assets/Carousel were changed
          if echo "$CHANGED_FILES" | grep -q "^Assets/Carousel/"; then
            echo "samples_changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "samples_changes_detected=false" >> $GITHUB_OUTPUT
          fi
          
          # Check if any files in Packages/com.rafaelcordoba.carousel were changed
          if echo "$CHANGED_FILES" | grep -q "^Packages/com.rafaelcordoba.carousel/"; then
            echo "package_changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "package_changes_detected=false" >> $GITHUB_OUTPUT
          fi
          
          # Determine if we should bump the version
          if [[ "${{ steps.check_changes.outputs.samples_changes_detected }}" == "true" || "${{ steps.check_changes.outputs.package_changes_detected }}" == "true" ]]; then
            echo "should_bump_version=true" >> $GITHUB_OUTPUT
          else
            echo "should_bump_version=false" >> $GITHUB_OUTPUT
          fi

      - name: Copy samples
        if: steps.check_changes.outputs.samples_changes_detected == 'true'
        run: |
          mkdir -p Packages/com.rafaelcordoba.carousel/Samples~/BasicCarousel
          cp -r Assets/Carousel/* Packages/com.rafaelcordoba.carousel/Samples~/BasicCarousel/
          
      - name: Update package version
        if: steps.check_changes.outputs.should_bump_version == 'true'
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(grep -o '"version": "[^"]*"' Packages/com.rafaelcordoba.carousel/package.json | cut -d'"' -f4)
          
          # Split version into major, minor, and patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          
          # Increment patch version
          NEW_PATCH=$((PATCH + 1))
          
          # Create new version string
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          
          # Update version in package.json
          sed -i "s/\"version\": \"$CURRENT_VERSION\"/\"version\": \"$NEW_VERSION\"/" Packages/com.rafaelcordoba.carousel/package.json
          
          # Output the new version for the commit message
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          
      - name: Commit changes
        if: steps.check_changes.outputs.should_bump_version == 'true'
        run: |
          if [ "${{ steps.check_changes.outputs.samples_changes_detected }}" == "true" ]; then
            git add Packages/com.rafaelcordoba.carousel/Samples~ Packages/com.rafaelcordoba.carousel/package.json
            git commit -m "updating samples and bumping version to $NEW_VERSION"
          else
            git add Packages/com.rafaelcordoba.carousel/package.json
            git commit -m "bumping version to $NEW_VERSION"
          fi
          git push 