name: Update Samples

on:
  push:
    branches:
      - master

jobs:
  update-samples:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Process changes and update package
        run: |
          # Get the list of changed files in the last commit
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          
          # Check if any files in Assets/Carousel were changed
          SAMPLES_CHANGED=false
          if echo "$CHANGED_FILES" | grep -q "^Assets/Carousel/"; then
            SAMPLES_CHANGED=true
          fi
          
          # Check if any files in Packages/com.rafaelcordoba.carousel were changed
          PACKAGE_CHANGED=false
          if echo "$CHANGED_FILES" | grep -q "^Packages/com.rafaelcordoba.carousel/"; then
            PACKAGE_CHANGED=true
          fi
          
          # Determine if we should bump the version
          BUMP_VERSION=false
          if [[ "$SAMPLES_CHANGED" == "true" || "$PACKAGE_CHANGED" == "true" ]]; then
            BUMP_VERSION=true
          fi
          
          # Copy samples if needed
          if [ "$SAMPLES_CHANGED" == "true" ]; then
            mkdir -p Packages/com.rafaelcordoba.carousel/Samples~/BasicCarousel
            cp -r Assets/Carousel/* Packages/com.rafaelcordoba.carousel/Samples~/BasicCarousel/
          fi
          
          # Update version if needed
          if [ "$BUMP_VERSION" == "true" ]; then
            # Get current version from package.json
            CURRENT_VERSION=$(grep -o '"version": "[^"]*"' Packages/com.rafaelcordoba.carousel/package.json | cut -d'"' -f4)
            
            # Split version into major, minor, and patch
            IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
            
            # Increment patch version
            NEW_PATCH=$((PATCH + 1))
            
            # Create new version string
            NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
            
            # Update version in package.json
            sed -i "s/\"version\": \"$CURRENT_VERSION\"/\"version\": \"$NEW_VERSION\"/" Packages/com.rafaelcordoba.carousel/package.json
            
            # Commit changes
            if [ "$SAMPLES_CHANGED" == "true" ]; then
              git add Packages/com.rafaelcordoba.carousel/Samples~ Packages/com.rafaelcordoba.carousel/package.json
              git commit -m "updating samples and bumping version to $NEW_VERSION"
            else
              git add Packages/com.rafaelcordoba.carousel/package.json
              git commit -m "bumping version to $NEW_VERSION"
            fi
            git push 