name: Update Samples

on:
  push:
    branches:
      - master
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-samples:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Check for changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            samples:
              - 'Assets/Carousel/**'
            package:
              - 'Packages/com.rafaelcordoba.carousel/**'
            
      - name: Copy samples
        if: steps.changes.outputs.samples == 'true'
        run: |
          mkdir -p Packages/com.rafaelcordoba.carousel/Samples~/BasicCarousel
          cp -r Assets/Carousel/* Packages/com.rafaelcordoba.carousel/Samples~/BasicCarousel/ || exit 1
          
      - name: Bump version
        if: steps.changes.outputs.package == 'true'
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(grep -o '"version": "[^"]*"' Packages/com.rafaelcordoba.carousel/package.json | cut -d'"' -f4)
          
          # Split version into major, minor, and patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          
          # Increment patch version
          NEW_PATCH=$((PATCH + 1))
          
          # Create new version string
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          
          # Update version in package.json
          sed -i "s/\"version\": \"$CURRENT_VERSION\"/\"version\": \"$NEW_VERSION\"/" Packages/com.rafaelcordoba.carousel/package.json
      
      - name: Commit and push samples changes
        if: steps.changes.outputs.samples == 'true'
        run: |
          git add Packages/com.rafaelcordoba.carousel/Samples~
          git commit -m "chore: update samples"
          git push

      - name: Commit and push version bump
        if: steps.changes.outputs.package == 'true'
        run: |
          git add Packages/com.rafaelcordoba.carousel/package.json
          git commit -m "chore: bump version to $NEW_VERSION"
          git push